"""
pdf_service.py — Professional Financial Health PDF Report generator using ReportLab.

Produces a multi-page, publication-grade fintech report containing:
  1. Executive Cover & Header with User Information
  2. Financial Health Overview & Key Credit Metrics
  3. Monthly Cash Flow Breakdown Table
  4. Core Calculated Health Ratios (Savings Rate, DTI)
  5. Gemini AI Financial Analysis (Summary, Critical Issues, 5 Actionable Recommendations)
  6. Credit, Savings, and Debt Advice Sections
  7. Expected Improvement Timeline Roadmap
  8. Educational Compliance Disclaimer & Footer
"""

import io
from datetime import datetime
from typing import Dict, Any, List

from reportlab.lib.pagesizes import letter
from reportlab.lib import colors
from reportlab.lib.units import inch
from reportlab.lib.styles import getSampleStyleSheet, ParagraphStyle
from reportlab.platypus import (
    SimpleDocTemplate,
    Paragraph,
    Spacer,
    Table,
    TableStyle,
    KeepTogether,
    HRFlowable
)
from reportlab.pdfgen import canvas


class NumberedCanvas(canvas.Canvas):
    """
    Two-pass canvas that accurately calculates the total page count
    and renders professional headers and footers with 'Page X of Y'.
    """

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._saved_page_states = []

    def showPage(self):
        self._saved_page_states.append(dict(self.__dict__))
        self._startPage()

    def save(self):
        num_pages = len(self._saved_page_states)
        for state in self._saved_page_states:
            self.__dict__.update(state)
            self.draw_page_decorations(num_pages)
            super().showPage()
        super().save()

    def draw_page_decorations(self, page_count):
        self.saveState()
        self.setFont("Helvetica", 8)
        self.setFillColor(colors.HexColor("#64748b"))

        # Running Header (pages after page 1)
        if self._pageNumber > 1:
            self.setStrokeColor(colors.HexColor("#e2e8f0"))
            self.setLineWidth(0.5)
            self.line(54, 745, letter[0] - 54, 745)
            self.drawString(54, 750, "CREDIT ASSISTANT  |  Financial Health Diagnostic Report")
            self.drawRightString(letter[0] - 54, 750, datetime.now().strftime("%B %d, %Y"))

        # Running Footer (all pages)
        self.setStrokeColor(colors.HexColor("#e2e8f0"))
        self.setLineWidth(0.5)
        self.line(54, 45, letter[0] - 54, 45)

        footer_text = "CONFIDENTIAL  —  Generated by Credit Assistant AI for Indian Personal Finance"
        self.drawString(54, 32, footer_text)
        page_str = f"Page {self._pageNumber} of {page_count}"
        self.drawRightString(letter[0] - 54, 32, page_str)

        self.restoreState()


def format_inr(amount: float) -> str:
    """Format numbers into clean Indian currency representation without font encoding issues."""
    try:
        val = int(round(amount))
        s = str(abs(val))
        sign = "-" if val < 0 else ""
        if len(s) <= 3:
            return f"{sign}Rs. {s}"
        last3 = s[-3:]
        remaining = s[:-3]
        out = ""
        while len(remaining) > 2:
            out = "," + remaining[-2:] + out
            remaining = remaining[:-2]
        if remaining:
            out = remaining + out
        return f"{sign}Rs. {out},{last3}"
    except Exception:
        return f"Rs. {amount}"


def generate_pdf_report(user_data: Dict[str, Any], profile_data: Dict[str, Any], ai_data: Dict[str, Any]) -> bytes:
    """
    Generates a complete, multi-page financial health report in PDF format.
    Returns the generated PDF as raw bytes.
    """
    buffer = io.BytesIO()

    # 54pt (0.75 in) margins on all sides
    doc = SimpleDocTemplate(
        buffer,
        pagesize=letter,
        leftMargin=54,
        rightMargin=54,
        topMargin=60,
        bottomMargin=55
    )

    styles = getSampleStyleSheet()

    # Custom typography styles
    title_style = ParagraphStyle(
        'ReportTitle',
        parent=styles['Heading1'],
        fontName='Helvetica-Bold',
        fontSize=22,
        leading=26,
        textColor=colors.HexColor('#0f172a'),
        spaceAfter=2
    )

    subtitle_style = ParagraphStyle(
        'ReportSubtitle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=10,
        leading=14,
        textColor=colors.HexColor('#0284c7'),
        spaceAfter=14,
        textTransform='uppercase'
    )

    h2_style = ParagraphStyle(
        'ReportH2',
        parent=styles['Heading2'],
        fontName='Helvetica-Bold',
        fontSize=12,
        leading=16,
        textColor=colors.HexColor('#0f172a'),
        spaceBefore=12,
        spaceAfter=6
    )

    body_style = ParagraphStyle(
        'ReportBody',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=9,
        leading=13,
        textColor=colors.HexColor('#334155')
    )

    bold_body_style = ParagraphStyle(
        'ReportBoldBody',
        parent=body_style,
        fontName='Helvetica-Bold',
        textColor=colors.HexColor('#0f172a')
    )

    summary_quote_style = ParagraphStyle(
        'SummaryQuote',
        parent=styles['Normal'],
        fontName='Helvetica-Oblique',
        fontSize=9.5,
        leading=14,
        textColor=colors.HexColor('#1e293b')
    )

    badge_style = ParagraphStyle(
        'BadgeStyle',
        parent=styles['Normal'],
        fontName='Helvetica-Bold',
        fontSize=8,
        leading=10,
        textColor=colors.HexColor('#0284c7'),
        alignment=1
    )

    disclaimer_style = ParagraphStyle(
        'DisclaimerStyle',
        parent=styles['Normal'],
        fontName='Helvetica',
        fontSize=7.5,
        leading=11,
        textColor=colors.HexColor('#64748b')
    )

    elements = []

    # -------------------------------------------------------------------------
    # 1. HEADER & BRAND BANNER
    # -------------------------------------------------------------------------
    header_table_data = [
        [
            Paragraph("CREDIT ASSISTANT", title_style),
            Paragraph(f"<b>Date:</b> {datetime.now().strftime('%d %b %Y')}<br/><b>Ref ID:</b> CA-USR{user_data.get('user_id', 1):04d}", ParagraphStyle('MetaRight', parent=body_style, alignment=2))
        ],
        [
            Paragraph("Comprehensive Financial Health & Credit Assessment Report", subtitle_style),
            ""
        ]
    ]
    header_table = Table(header_table_data, colWidths=[330, 174])
    header_table.setStyle(TableStyle([
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('SPAN', (0, 1), (1, 1)),
        ('LEFTPADDING', (0, 0), (-1, -1), 0),
        ('RIGHTPADDING', (0, 0), (-1, -1), 0),
        ('TOPPADDING', (0, 0), (-1, -1), 0),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 2),
    ]))
    elements.append(header_table)
    elements.append(HRFlowable(width="100%", thickness=1.5, color=colors.HexColor('#0284c7'), spaceBefore=4, spaceAfter=12))

    # -------------------------------------------------------------------------
    # 2. USER PROFILE & HEALTH SCORE HERO CARD
    # -------------------------------------------------------------------------
    credit_score = int(profile_data.get('credit_score', 740))
    salary = float(profile_data.get('monthly_salary', 75000.0))
    expenses = float(profile_data.get('monthly_expenses', 38000.0))
    savings = float(profile_data.get('monthly_savings', 20000.0))
    debt = float(profile_data.get('monthly_debt_payments', 17000.0))
    total_debt = float(profile_data.get('total_debt', 450000.0))
    utilization = float(profile_data.get('credit_utilization', 28.0))
    missed_payments = int(profile_data.get('missed_payments', 0))
    active_loans = int(profile_data.get('active_loans', 2))

    savings_rate = round((savings / salary * 100), 2) if salary > 0 else 0.0
    dti_ratio = round((debt / salary * 100), 2) if salary > 0 else 0.0

    # Determine health tier
    if credit_score >= 750 and dti_ratio <= 35 and missed_payments == 0:
        health_score_num = 86
        health_tier = "Excellent (Prime Tier)"
        tier_color = "#059669"
    elif credit_score >= 700 and dti_ratio <= 42:
        health_score_num = 74
        health_tier = "Good (Stable)"
        tier_color = "#0284c7"
    elif credit_score >= 650:
        health_score_num = 62
        health_tier = "Fair (Attention Needed)"
        tier_color = "#d97706"
    else:
        health_score_num = 45
        health_tier = "Critical (High Risk)"
        tier_color = "#dc2626"

    hero_card_data = [
        [
            Paragraph(f"<b>USER INFORMATION</b><br/>"
                      f"Name: <b>{user_data.get('name', 'Consumer')}</b><br/>"
                      f"Email: {user_data.get('email', 'consumer@example.in')}<br/>"
                      f"Mobile: {user_data.get('mobile', 'N/A')}<br/>"
                      f"Jurisdiction: India (INR / RBI Standards)", body_style),
            Paragraph(f"<font color='{tier_color}'><b>FINANCIAL HEALTH SCORE</b></font><br/>"
                      f"<font size='24' color='{tier_color}'><b>{health_score_num} / 100</b></font><br/>"
                      f"Status: <b>{health_tier}</b><br/>"
                      f"<font size='8' color='#64748b'>Synthesized from 10 Indian Credit Parameters</font>", ParagraphStyle('ScoreCenter', parent=body_style, alignment=1))
        ]
    ]
    hero_table = Table(hero_card_data, colWidths=[280, 224])
    hero_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#e2e8f0')),
        ('VALIGN', (0, 0), (-1, -1), 'MIDDLE'),
        ('TOPPADDING', (0, 0), (-1, -1), 10),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 10),
        ('LEFTPADDING', (0, 0), (-1, -1), 12),
        ('RIGHTPADDING', (0, 0), (-1, -1), 12),
    ]))
    elements.append(hero_table)
    elements.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 3. FINANCIAL HEALTH OVERVIEW & CALCULATED METRICS TABLE
    # -------------------------------------------------------------------------
    elements.append(Paragraph("1. Core Financial & Credit Standing Metrics", h2_style))

    metrics_table_data = [
        [
            Paragraph("<b>Metric</b>", bold_body_style),
            Paragraph("<b>User Value</b>", bold_body_style),
            Paragraph("<b>Benchmark / Target</b>", bold_body_style),
            Paragraph("<b>Status</b>", bold_body_style)
        ],
        [
            Paragraph("Credit Bureau Score (CIBIL)", body_style),
            Paragraph(f"<b>{credit_score}</b>", bold_body_style),
            Paragraph("750 - 900 (Prime)", body_style),
            Paragraph("Optimal" if credit_score >= 750 else "Good" if credit_score >= 700 else "Action Required", body_style)
        ],
        [
            Paragraph("Credit Utilization Ratio", body_style),
            Paragraph(f"<b>{utilization}%</b>", bold_body_style),
            Paragraph("&lt; 30% of card limits", body_style),
            Paragraph("Healthy" if utilization <= 30 else "High Burden", body_style)
        ],
        [
            Paragraph("Savings Rate", body_style),
            Paragraph(f"<b>{savings_rate}%</b>", bold_body_style),
            Paragraph("&ge; 20% of net salary", body_style),
            Paragraph("Strong" if savings_rate >= 20 else "Moderate" if savings_rate >= 10 else "Low", body_style)
        ],
        [
            Paragraph("Debt-to-Income (DTI) Ratio", body_style),
            Paragraph(f"<b>{dti_ratio}%</b>", bold_body_style),
            Paragraph("&lt; 35% of monthly salary", body_style),
            Paragraph("Safe" if dti_ratio <= 35 else "Elevated" if dti_ratio <= 45 else "High Debt Burden", body_style)
        ],
        [
            Paragraph("Missed Payments (Past 12m)", body_style),
            Paragraph(f"<b>{missed_payments}</b>", bold_body_style),
            Paragraph("0 Overdue installments", body_style),
            Paragraph("Flawless" if missed_payments == 0 else "Severe Impact", body_style)
        ],
        [
            Paragraph("Active Credit Accounts", body_style),
            Paragraph(f"<b>{active_loans} Loan(s)</b>", bold_body_style),
            Paragraph("Diversified mix", body_style),
            Paragraph("Active", body_style)
        ]
    ]

    metrics_table = Table(metrics_table_data, colWidths=[174, 100, 130, 100])
    metrics_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
    ]))
    elements.append(metrics_table)
    elements.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 4. MONTHLY CASH FLOW SUMMARY
    # -------------------------------------------------------------------------
    elements.append(Paragraph("2. Monthly Cash Flow & Principal Obligations", h2_style))

    surplus = salary - expenses - debt - savings
    cashflow_data = [
        [
            Paragraph("<b>Monthly Salary (Net Take-Home)</b>", bold_body_style),
            Paragraph(f"<b>{format_inr(salary)}</b>", bold_body_style),
            Paragraph("<b>Total Outstanding Principal</b>", bold_body_style),
            Paragraph(f"<b>{format_inr(total_debt)}</b>", bold_body_style)
        ],
        [
            Paragraph("Living Essentials & Expenses", body_style),
            Paragraph(format_inr(expenses), body_style),
            Paragraph("Monthly Debt EMIs", body_style),
            Paragraph(format_inr(debt), body_style)
        ],
        [
            Paragraph("Monthly Savings & SIPs", body_style),
            Paragraph(format_inr(savings), body_style),
            Paragraph("Unallocated Surplus / Buffer", body_style),
            Paragraph(f"<b>{format_inr(surplus)}</b>", bold_body_style)
        ]
    ]

    cashflow_table = Table(cashflow_data, colWidths=[160, 92, 160, 92])
    cashflow_table.setStyle(TableStyle([
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('BACKGROUND', (0, 0), (1, 0), colors.HexColor('#f1f5f9')),
        ('BACKGROUND', (2, 0), (3, 0), colors.HexColor('#fee2e2')),
        ('TOPPADDING', (0, 0), (-1, -1), 5),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
    ]))
    elements.append(cashflow_table)
    elements.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 5. AI EXECUTIVE SUMMARY & CRITICAL ISSUES
    # -------------------------------------------------------------------------
    elements.append(Paragraph("3. AI Financial Advisor Diagnostic (Powered by Google Gemini)", h2_style))

    summary_text = ai_data.get("summary", "Your financial profile indicates stable baseline fundamentals with clear optimization avenues.")
    summary_card = [
        [
            Paragraph("<b>AI EXECUTIVE SUMMARY:</b><br/>" + summary_text, summary_quote_style)
        ]
    ]
    summary_table = Table(summary_card, colWidths=[504])
    summary_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f0fdf4')),
        ('BOX', (0, 0), (-1, -1), 1, colors.HexColor('#86efac')),
        ('LEFTPADDING', (0, 0), (-1, -1), 10),
        ('RIGHTPADDING', (0, 0), (-1, -1), 10),
        ('TOPPADDING', (0, 0), (-1, -1), 8),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 8),
    ]))
    elements.append(summary_table)
    elements.append(Spacer(1, 10))

    # Critical Issues
    critical_issues = ai_data.get("critical_issues", [])
    if critical_issues:
        elements.append(Paragraph("<b>TOP CRITICAL ISSUES IDENTIFIED:</b>", ParagraphStyle('SubSub', parent=bold_body_style, textColor=colors.HexColor('#dc2626'))))
        issue_rows = []
        for idx, issue in enumerate(critical_issues[:3], 1):
            issue_rows.append([
                Paragraph(f"<font color='#dc2626'><b>#{idx}</b></font>", ParagraphStyle('IssueNum', parent=bold_body_style, alignment=1)),
                Paragraph(issue, body_style)
            ])
        issues_table = Table(issue_rows, colWidths=[30, 474])
        issues_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#fef2f2')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#fecaca')),
            ('TOPPADDING', (0, 0), (-1, -1), 5),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 5),
        ]))
        elements.append(issues_table)
        elements.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 6. ACTIONABLE RECOMMENDATIONS (5 ITEMS)
    # -------------------------------------------------------------------------
    elements.append(Paragraph("4. Actionable Financial Health Recommendations", h2_style))

    recommendations = ai_data.get("recommendations", [])
    rec_table_data = [
        [
            Paragraph("<b>#</b>", bold_body_style),
            Paragraph("<b>Category & Priority</b>", bold_body_style),
            Paragraph("<b>Strategic Measure & Action Steps</b>", bold_body_style),
            Paragraph("<b>Estimated Impact</b>", bold_body_style)
        ]
    ]

    for idx, rec in enumerate(recommendations[:5], 1):
        category = rec.get("category", "General")
        priority = rec.get("priority", "Medium")
        title = rec.get("title", "")
        description = rec.get("description", "")
        impact = rec.get("impact", "")
        actions = rec.get("action_plan", rec.get("actionPlan", []))

        action_bullets = "<br/>".join([f"&bull; {act}" for act in actions[:2]]) if actions else ""

        rec_content = f"<b>{title}</b><br/>{description}"
        if action_bullets:
            rec_content += f"<br/><font size='8' color='#0284c7'><b>Action Steps:</b></font><br/>{action_bullets}"

        priority_color = "#dc2626" if priority == "Critical" else "#d97706" if priority == "High" else "#0284c7"

        rec_table_data.append([
            Paragraph(f"<b>{idx}</b>", bold_body_style),
            Paragraph(f"<b>{category}</b><br/><font color='{priority_color}'><b>[{priority}]</b></font>", body_style),
            Paragraph(rec_content, body_style),
            Paragraph(f"<b>{impact}</b>", body_style)
        ])

    rec_table = Table(rec_table_data, colWidths=[20, 110, 254, 120])
    rec_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#0f172a')),
        ('TEXTCOLOR', (0, 0), (-1, 0), colors.white),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#cbd5e1')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ('ROWBACKGROUNDS', (0, 1), (-1, -1), [colors.white, colors.HexColor('#f8fafc')]),
    ]))
    elements.append(rec_table)
    elements.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 7. DOMAIN ADVICE & IMPROVEMENT TIMELINE
    # -------------------------------------------------------------------------
    elements.append(Paragraph("5. Domain Strategy & Improvement Milestones", h2_style))

    credit_adv = "<br/>&bull; ".join(ai_data.get("credit_advice", ["Keep utilization under 30%", "Preserve older credit accounts"]))
    savings_adv = "<br/>&bull; ".join(ai_data.get("savings_advice", ["Automate 20% savings", "Build 6-month buffer"]))
    debt_adv = "<br/>&bull; ".join(ai_data.get("debt_advice", ["Prioritize high-interest loans", "Cap DTI under 35%"]))

    advice_card_data = [
        [
            Paragraph("<b>CREDIT BUREAU ADVICE</b><br/>&bull; " + credit_adv, body_style),
            Paragraph("<b>SAVINGS & WEALTH ADVICE</b><br/>&bull; " + savings_adv, body_style),
            Paragraph("<b>DEBT MANAGEMENT ADVICE</b><br/>&bull; " + debt_adv, body_style)
        ]
    ]
    advice_table = Table(advice_card_data, colWidths=[168, 168, 168])
    advice_table.setStyle(TableStyle([
        ('BACKGROUND', (0, 0), (-1, -1), colors.HexColor('#f8fafc')),
        ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#e2e8f0')),
        ('TOPPADDING', (0, 0), (-1, -1), 6),
        ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
        ('VALIGN', (0, 0), (-1, -1), 'TOP'),
    ]))
    elements.append(advice_table)
    elements.append(Spacer(1, 10))

    # Timeline Roadmap
    timeline = ai_data.get("improvement_timeline", [])
    if timeline:
        timeline_headers = []
        timeline_cells = []
        for step in timeline[:4]:
            period = step.get("period", "")
            milestone = step.get("milestone", "")
            outcome = step.get("expected_outcome", "")
            timeline_headers.append(Paragraph(f"<b>{period}</b>", ParagraphStyle('TimeHead', parent=bold_body_style, textColor=colors.HexColor('#0284c7'), alignment=1)))
            timeline_cells.append(Paragraph(f"<b>{milestone}</b><br/><font size='8' color='#64748b'>{outcome}</font>", body_style))

        timeline_table = Table([timeline_headers, timeline_cells], colWidths=[126, 126, 126, 126])
        timeline_table.setStyle(TableStyle([
            ('BACKGROUND', (0, 0), (-1, 0), colors.HexColor('#e0f2fe')),
            ('GRID', (0, 0), (-1, -1), 0.5, colors.HexColor('#bae6fd')),
            ('TOPPADDING', (0, 0), (-1, -1), 6),
            ('BOTTOMPADDING', (0, 0), (-1, -1), 6),
            ('VALIGN', (0, 0), (-1, -1), 'TOP'),
        ]))
        elements.append(timeline_table)
        elements.append(Spacer(1, 14))

    # -------------------------------------------------------------------------
    # 8. REGULATORY & EDUCATIONAL DISCLAIMER
    # -------------------------------------------------------------------------
    elements.append(HRFlowable(width="100%", thickness=0.5, color=colors.HexColor('#cbd5e1'), spaceBefore=8, spaceAfter=8))
    elements.append(Paragraph(
        "<b>Educational Compliance Notice:</b> This diagnostic report is synthesized by Credit Assistant AI for educational "
        "and planning purposes only under Indian personal finance frameworks. It does not constitute licensed financial advisory, "
        "credit guarantee, or investment solicitation under SEBI / RBI statutory regulations. Consumers are advised to review "
        "independent loan agreements and official CIBIL/Experian credit records before executing credit consolidation decisions.",
        disclaimer_style
    ))

    # Build the PDF using the custom NumberedCanvas
    doc.build(elements, canvasmaker=NumberedCanvas)
    buffer.seek(0)
    return buffer.getvalue()
